name: redlenshoescleaning
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.7.1
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.2
  google_fonts: ^5.1.0
  flutter_datetime_picker: ^1.5.1
  intl: ^0.18.1
  animated_splash_screen: ^1.3.0
  animated_size_and_fade: ^3.0.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/LoginPage.png
    - assets/image/LogoRedlen.png

flutter_icons:
  android: true
  ios: false
  image_path: "@mipmap/logo.png"
